/* eslint-disable react/prop-types */
import { Poppins } from "next/font/google";
import "./globals.css";
import React from "react";

const poppins = Poppins({
  weight: ["400", "600", "500"],
  subsets: ["latin"],
});

export const metadata = {
  title: "JF products",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>{children}</body>
    </html>
  );
}
